name: DynamicWorldBorder
version: 3.0
main: org.dan.dynamicborder.DynamicBorderPlugin
api-version: '1.21'
author: Dan
description: Динамические мировые границы с экономикой

commands:
  border:
    description: Основная команда управления границами
    usage: |
      /border help - Показать помощь
      /border expand <количество> - Расширить границу
      /border shrink <количество> - Сузить границу
      /border info - Информация о границе
      /border speed <up|down> - Изменить скорость
      /border damage <up|down> - Изменить урон
      /border select <мир> - Выбрать мир
    aliases: [wb, worldborder, dynborder]

  borderadmin:
    description: Административные команды
    usage: |
      /borderadmin reload - Перезагрузить конфиги
      /borderadmin set <параметр> <значение> - Установить параметр
      /borderadmin limits <мир> - Показать лимиты мира
      /borderadmin reset <мир> - Сбросить настройки мира
      /borderadmin save - Сохранить все данные
    aliases: [wbadmin, wba, bordera]

  bordertest:
    description: Тестовые команды (для разработки)
    usage: /bordertest
    permission: dynamicborder.admin

permissions:
  dynamicborder.use:
    description: Разрешает использовать основные команды границ
    default: true

  dynamicborder.admin:
    description: Полный доступ к админ-командам
    default: op

  dynamicborder.expand:
    description: Разрешает расширять границы
    default: true

  dynamicborder.shrink:
    description: Разрешает сужать границы
    default: true

  dynamicborder.upgrade:
    description: Разрешает улучшать границы
    default: true